test/input,test: put all tests in the whitelist but then check if they exist
this avoids the issue where tests may or may not be built depending on the
cmake settings

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -8,8 +8,10 @@ declare count=0
 mkdir -p $output_dir
 
 grep "^[^#]" | while read unit_test; do
-    $unit_test >&2 \
-        && echo "test[$count]/status=\"$unit_test:success\"" \
-        || echo "test[$count]/status=\"$unit_test:failed\""
-    (( count++ ))
+    if type -p $unit_test >/dev/null; then
+        $unit_test >&2 \
+            && echo "test[$count]/status=\"$unit_test:success\"" \
+            || echo "test[$count]/status=\"$unit_test:failed\""
+        (( count++ ))
+    fi
 done
